version: '3.9'

services:
  backend:
    build:
      context: ..
      shm_size: '2gb'
      dockerfile: .devcontainer/Dockerfile
    shm_size: '2gb'
    volumes:
      - ../..:/workspaces:cached
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    privileged: true
  